Fix regression when Mysql user password is not set
The error was:

       … while calling anonymous lambda

         at /nix/store/s0nrb80miw28kw7ni6ia05fk5ckmyiaw-source/src/modules/services/mysql.nix:114:25:

          113|
          114|     ${concatMapStrings (user: ''
             |                         ^
          115|         echo "Adding user: ${user.name}"

       error: cannot coerce null to a string